name: Release Please

on:
  push:
    branches:
      - development
      - staging
      - "releases/**"
jobs:
  release-please:
    name: Release Please
    runs-on: ubuntu-latest
    steps:
      - name: Run Release Please Action
        uses: google-github-actions/release-please-action@v3
        with:
          target-branch: ${{ github.ref_name }}
          config-file: ${{ github.ref == 'refs/heads/staging' && 'release-please-staging-config.json' || 'release-please-config.json' }}
          manifest-file: ".release-please-manifest.json"
